name: Minify all JS files

on:
  push:
    branches:
      - '**'

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Terser
        run: npm install -g terser

      - name: Minify all .js files (excluding .min.js)
        run: |
          shopt -s globstar nullglob
          for file in **/*.js; do
            if [[ "$file" != *.min.js ]]; then
              minified="${file%.js}.min.js"
              echo "Minifying $file -> $minified"
              terser "$file" -o "$minified" --compress --mangle
            fi
          done

      - name: Commit and push minified files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git add '*.min.js'
          git commit -m "Auto-minified JS files on push to ${{ github.ref_name }}" || echo "Nothing to commit"
          git push origin HEAD:${{ github.ref_name }}
